plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.devtools.ksp)
}

android {
    namespace = "com.Jhon.myempty.blogdenotasjava"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.Jhon.myempty.blogdenotasjava"
        minSdk = 23
        targetSdk = 36
        versionCode = 1111
        versionName = "1.11.1"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.documentfile)
    implementation(libs.androidx.recyclerview)
    implementation(libs.glide)
    
    // Añadida para la serialización y deserialización de objetos Nota a formato JSON
    implementation("com.google.code.gson:gson:2.10.1")

    // Use KSP for Glide 5.x annotation processing
    ksp("com.github.bumptech.glide:ksp:5.0.5")
}